#!/bin/bash
#                                                     #
#  Author: Justin Goldsmith                           #
#  File: resundo.sh                                   #
#  Purpose:                                           #
#		- Remove restrictions for all extended users  #
#		- Delete extended user accounts               #
#		- Remove installed packages                   #
#		- Remove modifactions to modified packages    #
#                                                     #
#######################################################


#--Imports functions defined in resmake.sh
##########################################
. resmake.sh


#--These are set as variables because they are command line utilities
#--that will otherwise be interpreted asn run when used in the script
#####################################################################
PASS_CHANGE="passwd"
DEV_MAKE="make"
CHANGE_PERMS="chmod"
REPOSITORIES="add-apt-repository"
APT_GET="apt-get"


#--Creates a cowntdown timer that will display a countdown while
#--instructional portions of the script are displayed.
######################################################
function countdown() {
	for ((i=$1; i>0; i--)); do
	case $1 in
	30)
	    	echo -en "Computer will restart in: " $i " ...press any key to continue...\r"
		;;
	[5,10,20]*)
		echo -en "Automation will resume in: " $i "  Press any key to coninue...\r"
		;;
	esac
	sleep .3
	read -s -n 1 -t 1 key
    	if [ $? -eq 0 ]; then
		clear
        	break
    	fi
	done
	clear
}

#--Function to remove packages and configurations associated with x11vnc
#--and remove x11vnc configuration files
########################################
function remove_vnc_only() {
	sudo apt-get remove --purge x11vnc
	sudo rm /etc/x11vnc.pass
	sudo rm /etc/init/x11vnc.conf
	sudo rm /usr/shared/applications/x11vnc.desktop
}

#--Function to remove packages and configurations associated
#--with both x11vnc and ssh/sshd
################################
function remove_vnc_ssh() {
	sudo apt-get remove --purge openssh && sudo apt-get remove --purge opensshd
	sudo apt-get remove --purge x11vnc
	sudo rm /etc/x11vnc.pass
	sudo rm /etc/init/x11vnc.conf
	sudo rm /usr/shared/applications/x11vnc.desktop
}



set -e

#--The following lines will remove the ACL restrictions for each of the
#--restricted programs from the Access Control List. This really has no
#--necessary function other than cleaning up the Access Control List
#--which would otherwise have leftover ACL entries for phantom users.
#
#--                  !!!DO NOT EDIT THIS FILE!!!
#--TO ADD ACL RESTRICTED APPS: ADD THE APP PATH ENTRY TO resapps.txt
#--TO ALLOW AN APP: REMOVE THE APP PATH ENTRY FROM resapps.txt
#####################################################################
IFS=$'\n' resapps=($(< libs/resapps.txt))

for i in ${resapps[@]}; do
	echo "Removing restrictions for ${i}..."
	sudo setfacl -x u:jobsearch ${i}
	echo ""
done

sleep 5


#Delete the user account
########################
echo ""
echo ""
echo ""
echo -ne "Removing user: Public User"
sudo deluser jobsearch --remove-home
sleep 5
echo ""
echo ""
echo -ne "Removing Public User home directory"
sleep 5


#--Removing SSH or VNC (or both/neither) is optional. It is suggested
#--that you remove both unless you plan to use this machine for similar
#--applications in the future.
#--Alternatively, you can remove Teamviewer if you chose to install it.
#
#--If you choose to remove SSH or VNC (or both) because you no longer need
#--remote access to this machine - you should remember to close the port
#--associated with this machines remote configuration unless you plan to 
#--utilize that port again.
###########################
echo ""
echo ""
echo "We need to remove x11vnc and/or ssh. Please select how you initially"
echo "installed those settings."
echo ""
echo ""
echo "1. SSH Only"
echo "2. VNC Only"
echo "3. Both"
echo "4. Teamviewer"
echo "5. Neither"
echo ""
read -p "> " remote

case $remote in
1)
	sudo apt-get remove --purge openssh && sudo apt-get remove --purge opensshd
	;;
2)
	remove_vnc_only
	;;
3)
	remove_vnc_ssh
	;;
4)
	sudo apt-get remove --purge teamviewer
	;;
5)
	echo "Nothing to remove. Moving on..."
	countdown 10
esac

echo " "
echo " "
echo "Operation Complete."
echo " "
echo " "

exit 0
